package com.wefky.RESTfulWeb.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Represents an Image or file in the database.
 */
@Entity
@Table(name = "images")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Image {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "image_id")
    private Long imageId;

    @Column(name = "owner", length = 100)
    private String owner;

    @Lob
    @Basic(fetch = FetchType.EAGER)
    @Column(name = "data", nullable = false)
    private byte[] data;

    @Column(name = "deleted", nullable = false)
    private boolean deleted = false;

    @Column(name = "content_type", length = 50)
    private String contentType;

    @Column(name = "title", length = 255)
    private String title;

    @Column(name = "description", length = 500)
    private String description;

    @Column(name = "upload_date", nullable = false)
    private LocalDateTime uploadDate;

    /**
     * Transient field to store base64-encoded data, so the Thymeleaf template
     * doesn't need to call T(...) to do the encoding.
     */
    @Transient
    private String base64Data;

    // If you are NOT using Lombok's @Data, add the getters/setters manually:
    // public String getBase64Data() { return base64Data; }
    // public void setBase64Data(String base64Data) { this.base64Data = base64Data; }

    // ...all other getters/setters generated by Lombok or manually as needed...
}
